import type { GenColumnInfoOperationRequest } from '@/model/generate/column.model.ts'
import { LanguageTypeEnums } from '@/model/generate/common.model.ts'

const columnData: GenColumnInfoOperationRequest[] = [
  {
    id: '1',
    tableId: '1001',
    columnName: 'id',
    dbDataType: 'MySql',
    columnComment: '主键ID',
    defaultValue: '',
    isRequired: 1,
    isPrimary: 1,
    sortOrder: 1,
    extConfig: {
      formItem: '1',
      formRequired: '1',
      formType: 'input',
      gridItem: '1',
      gridSort: '1',
      queryItem: '1',
      queryType: 'eq',
      queryFormType: 'input',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'Long',
          importPackage: '',
          defaultValue: 'null',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'number',
          importPackage: '',
          defaultValue: '0',
        },
      ],
    },
  },
  {
    id: '2',
    tableId: '1001',
    columnName: 'username',
    dbDataType: 'MySql',
    columnComment: '用户名',
    defaultValue: '',
    isRequired: 1,
    isPrimary: 0,
    sortOrder: 2,
    extConfig: {
      formItem: '1',
      formRequired: '1',
      formType: 'input',
      gridItem: '1',
      gridSort: '1',
      queryItem: '1',
      queryType: 'like',
      queryFormType: 'input',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'String',
          importPackage: '',
          defaultValue: '""',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'string',
          importPackage: '',
          defaultValue: "''",
        },
      ],
    },
  },
  {
    id: '3',
    tableId: '1001',
    columnName: 'create_time',
    dbDataType: 'MySql',
    columnComment: '创建时间',
    defaultValue: 'CURRENT_TIMESTAMP',
    isRequired: 1,
    isPrimary: 0,
    sortOrder: 3,
    extConfig: {
      formItem: '1',
      formRequired: '0',
      formType: 'datetime-picker',
      gridItem: '1',
      gridSort: '1',
      queryItem: '1',
      queryType: 'between',
      queryFormType: 'date-range',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'LocalDateTime',
          importPackage: 'java.time.LocalDateTime',
          defaultValue: 'LocalDateTime.now()',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'Date',
          importPackage: '',
          defaultValue: 'new Date()',
        },
      ],
    },
  },
  {
    id: '4',
    tableId: '1001',
    columnName: 'status',
    dbDataType: 'MySql',
    columnComment: '状态',
    defaultValue: '1',
    isRequired: 1,
    isPrimary: 0,
    sortOrder: 4,
    extConfig: {
      formItem: '1',
      formRequired: '1',
      formType: 'select',
      gridItem: '1',
      gridSort: '1',
      queryItem: '1',
      queryType: 'eq',
      queryFormType: 'select',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'Integer',
          importPackage: '',
          defaultValue: '1',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'number',
          importPackage: '',
          defaultValue: '1',
        },
      ],
    },
  },
  {
    id: '5',
    tableId: '1001',
    columnName: 'remark',
    dbDataType: 'MySql',
    columnComment: '备注',
    defaultValue: '',
    isRequired: 0,
    isPrimary: 0,
    sortOrder: 5,
    extConfig: {
      formItem: '1',
      formRequired: '0',
      formType: 'textarea',
      gridItem: '0',
      gridSort: '0',
      queryItem: '0',
      queryType: '',
      queryFormType: '',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'String',
          importPackage: '',
          defaultValue: '""',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'string',
          importPackage: '',
          defaultValue: "''",
        },
      ],
    },
  },
  {
    id: '6',
    tableId: '1001',
    columnName: 'user_age',
    dbDataType: 'MySql',
    columnComment: '用户年龄',
    defaultValue: '18',
    isRequired: 0,
    isPrimary: 0,
    sortOrder: 6,
    extConfig: {
      formItem: '1',
      formRequired: '0',
      formType: 'number',
      gridItem: '1',
      gridSort: '1',
      queryItem: '1',
      queryType: 'between',
      queryFormType: 'number-range',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'Integer',
          importPackage: '',
          defaultValue: '18',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'int',
          importPackage: '',
          defaultValue: '18',
        },
      ],
    },
  },
  {
    id: '7',
    tableId: '1001',
    columnName: 'email',
    dbDataType: 'Oracle',
    columnComment: '电子邮箱',
    defaultValue: '',
    isRequired: 1,
    isPrimary: 0,
    sortOrder: 7,
    extConfig: {
      formItem: '1',
      formRequired: '1',
      formType: 'input',
      gridItem: '1',
      gridSort: '0',
      queryItem: '1',
      queryType: 'like',
      queryFormType: 'input',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'String',
          importPackage: '',
          defaultValue: '""',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'string',
          importPackage: '',
          defaultValue: "''",
        },
      ],
    },
  },
  {
    id: '8',
    tableId: '1001',
    columnName: 'phone',
    dbDataType: 'MySql',
    columnComment: '手机号码',
    defaultValue: '',
    isRequired: 0,
    isPrimary: 0,
    sortOrder: 8,
    extConfig: {
      formItem: '1',
      formRequired: '0',
      formType: 'input',
      gridItem: '1',
      gridSort: '0',
      queryItem: '1',
      queryType: 'eq',
      queryFormType: 'input',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'String',
          importPackage: '',
          defaultValue: '""',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'str',
          importPackage: '',
          defaultValue: "''",
        },
      ],
    },
  },
  {
    id: '9',
    tableId: '1001',
    columnName: 'gender',
    dbDataType: 'Oracle',
    columnComment: '性别',
    defaultValue: '0',
    isRequired: 1,
    isPrimary: 0,
    sortOrder: 9,
    extConfig: {
      formItem: '1',
      formRequired: '1',
      formType: 'radio',
      gridItem: '1',
      gridSort: '1',
      queryItem: '1',
      queryType: 'eq',
      queryFormType: 'select',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'Integer',
          importPackage: '',
          defaultValue: '0',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'number',
          importPackage: '',
          defaultValue: '0',
        },
      ],
    },
  },
  {
    id: '10',
    tableId: '1001',
    columnName: 'address',
    dbDataType: 'MySql',
    columnComment: '家庭地址',
    defaultValue: '',
    isRequired: 0,
    isPrimary: 0,
    sortOrder: 10,
    extConfig: {
      formItem: '1',
      formRequired: '0',
      formType: 'textarea',
      gridItem: '0',
      gridSort: '0',
      queryItem: '0',
      queryType: '',
      queryFormType: '',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'String',
          importPackage: '',
          defaultValue: '""',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'str',
          importPackage: '',
          defaultValue: "''",
        },
      ],
    },
  },
  {
    id: '11',
    tableId: '1001',
    columnName: 'is_vip',
    dbDataType: 'Oracle',
    columnComment: '是否VIP',
    defaultValue: '0',
    isRequired: 1,
    isPrimary: 0,
    sortOrder: 11,
    extConfig: {
      formItem: '1',
      formRequired: '1',
      formType: 'switch',
      gridItem: '1',
      gridSort: '1',
      queryItem: '1',
      queryType: 'eq',
      queryFormType: 'select',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'Boolean',
          importPackage: '',
          defaultValue: 'false',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'boolean',
          importPackage: '',
          defaultValue: 'false',
        },
      ],
    },
  },
  {
    id: '12',
    tableId: '1001',
    columnName: 'last_login_time',
    dbDataType: 'MySql',
    columnComment: '最后登录时间',
    defaultValue: '',
    isRequired: 0,
    isPrimary: 0,
    sortOrder: 12,
    extConfig: {
      formItem: '0',
      formRequired: '0',
      formType: 'datetime-picker',
      gridItem: '1',
      gridSort: '1',
      queryItem: '1',
      queryType: 'between',
      queryFormType: 'date-range',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'LocalDateTime',
          importPackage: 'java.time.LocalDateTime',
          defaultValue: 'null',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'datetime',
          importPackage: 'datetime',
          defaultValue: 'None',
        },
      ],
    },
  },
  {
    id: '13',
    tableId: '1001',
    columnName: 'role_ids',
    dbDataType: 'Oracle',
    columnComment: '角色ID集合',
    defaultValue: '',
    isRequired: 0,
    isPrimary: 0,
    sortOrder: 13,
    extConfig: {
      formItem: '1',
      formRequired: '0',
      formType: 'checkbox',
      gridItem: '0',
      gridSort: '0',
      queryItem: '1',
      queryType: 'in',
      queryFormType: 'select-multiple',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'List<Long>',
          importPackage: 'java.util.List',
          defaultValue: 'new ArrayList<>()',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'number[]',
          importPackage: '',
          defaultValue: '[]',
        },
      ],
    },
  },
  {
    id: '14',
    tableId: '1001',
    columnName: 'avatar_url',
    dbDataType: 'MySql',
    columnComment: '头像URL',
    defaultValue: '',
    isRequired: 0,
    isPrimary: 0,
    sortOrder: 14,
    extConfig: {
      formItem: '1',
      formRequired: '0',
      formType: 'upload',
      gridItem: '1',
      gridSort: '0',
      queryItem: '0',
      queryType: '',
      queryFormType: '',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'String',
          importPackage: '',
          defaultValue: '""',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'str',
          importPackage: '',
          defaultValue: "''",
        },
      ],
    },
  },
  {
    id: '15',
    tableId: '1001',
    columnName: 'balance',
    dbDataType: 'Oracle',
    columnComment: '账户余额',
    defaultValue: '0.00',
    isRequired: 1,
    isPrimary: 0,
    sortOrder: 15,
    extConfig: {
      formItem: '1',
      formRequired: '1',
      formType: 'number',
      gridItem: '1',
      gridSort: '1',
      queryItem: '1',
      queryType: 'between',
      queryFormType: 'number-range',
      typeMappings: [
        {
          languageType: LanguageTypeEnums.JAVA,
          columnType: 'BigDecimal',
          importPackage: 'java.math.BigDecimal',
          defaultValue: 'BigDecimal.ZERO',
        },
        {
          languageType: LanguageTypeEnums.TYPESCRIPT,
          columnType: 'number',
          importPackage: '',
          defaultValue: '0',
        },
      ],
    },
  },
]

export default columnData
