import type { DepOptimizationOptions } from 'vite'

/**
 * Element Plus 预加载组件样式（按需优化）
 * 列表需与 vite.config.ts 中 ElementPlusResolver 的 importStyle 保持一致：
 * - importStyle: 'sass' => 'element-plus/es/components/${name}/style/index'
 * - importStyle: 'css'  => 'element-plus/es/components/${name}/style/css'
 * 路径不匹配时，这些样式模块会直到首次访问相关页面才被 Vite 运行时发现，
 * 触发重新预构建并整页刷新（即“切换路由时偶发页面重新加载”）
 */
const elementPlusPreloadStyles: string[] = [
  'alert',
  'aside',
  'autocomplete',
  'avatar',
  'badge',
  'base',
  'breadcrumb',
  'breadcrumb-item',
  'button',
  'card',
  'checkbox',
  'checkbox-button',
  'checkbox-group',
  'col',
  'collapse',
  'collapse-item',
  'color-picker',
  'config-provider',
  'container',
  'date-picker',
  'descriptions',
  'descriptions-item',
  'dialog',
  'divider',
  'drawer',
  'dropdown',
  'dropdown-item',
  'dropdown-menu',
  'empty',
  'footer',
  'form',
  'form-item',
  'header',
  'icon',
  'image',
  'image-viewer',
  'input',
  'input-number',
  'input-tag',
  'link',
  'loading',
  'main',
  'menu',
  'menu-item',
  'message',
  'message-box',
  'notification',
  'option',
  'pagination',
  'popover',
  'progress',
  'radio',
  'radio-button',
  'radio-group',
  'rate',
  'row',
  'scrollbar',
  'select',
  'skeleton',
  'skeleton-item',
  'space',
  'splitter',
  'splitter-panel',
  'statistic',
  'step',
  'steps',
  'sub-menu',
  'switch',
  'tab-pane',
  'table',
  'table-column',
  'tabs',
  'tag',
  'text',
  'timeline',
  'timeline-item',
  'tooltip',
  'transfer',
  'tree',
  'tree-select',
  'upload',
  'watermark',
].map((component) => `element-plus/es/components/${component}/style/index`)

/**
 * 预加载项目必需的组件
 */
export default function (): DepOptimizationOptions {
  return {
    include: [
      'vue',
      'vue-router',
      'element-plus',
      // unplugin-vue-components 按需导入组件时使用的主入口
      'element-plus/es',
      // 中文语言包为独立子路径导入（App.vue）
      'element-plus/es/locale/lang/zh-cn',
      'pinia',
      'pinia-plugin-persistedstate',
      'axios',
      '@vueuse/core',
      'qs',
      'nprogress',
      'lodash',
      'sortablejs',
      '@element-plus/icons-vue',
      // monaco-editor 主包被懒加载页面引用，未预构建时首次进入相关路由会触发 Vite 全量刷新
      'monaco-editor',
      `monaco-editor/esm/vs/language/json/json.worker`,
      `monaco-editor/esm/vs/language/css/css.worker`,
      `monaco-editor/esm/vs/language/html/html.worker`,
      `monaco-editor/esm/vs/language/typescript/ts.worker`,
      `monaco-editor/esm/vs/editor/editor.worker`,
      ...elementPlusPreloadStyles,
    ],
  }
}
