import type { DepOptimizationOptions } from 'vite'

/**
 * Element Plus 预加载组件样式（按需优化）
 */
const elementPlusPreloadStyles: string[] = [
  'form',
  'form-item',
  'button',
  'input',
  'input-number',
  'switch',
  'upload',
  'menu2',
  'col',
  'icon',
  'row',
  'tag',
  'dialog',
  'loading',
  'radio',
  'radio-group',
  'popover',
  'scrollbar',
  'tooltip',
  'dropdown',
  'dropdown-menu2',
  'dropdown-item',
  'sub-menu2',
  'menu2-item',
  'divider',
  'card',
  'link',
  'breadcrumb',
  'breadcrumb-item',
  'table',
  'tree-select',
  'table-column',
  'select',
  'option',
  'pagination',
  'tree',
  'alert',
  'radio-button',
  'checkbox-group',
  'checkbox',
  'tabs',
  'tab-pane',
  'rate',
  'date-picker',
  'notification',
  'image',
  'statistic',
  'watermark',
  'config-provider',
  'text',
  'drawer',
  'color-picker',
  'message-box',
  'skeleton',
  'skeleton-item',
  'badge',
  'steps',
  'step',
  'avatar',
  'descriptions',
  'descriptions-item',
  'progress',
  'image-viewer',
  'empty',
].map((component) => `element-plus/es/components/${component}/style/css`)

/**
 * 预加载项目必需的组件
 */
export default function (): DepOptimizationOptions {
  return {
    include: [
      'vue',
      'vue-router',
      'element-plus',
      'pinia',
      'axios',
      '@vueuse/core',
      'path-to-regexp',
      'path-browserify',
      `monaco-editor/esm/vs/language/json/json.worker`,
      `monaco-editor/esm/vs/language/css/css.worker`,
      `monaco-editor/esm/vs/language/html/html.worker`,
      `monaco-editor/esm/vs/language/typescript/ts.worker`,
      `monaco-editor/esm/vs/editor/editor.worker`,
      ...elementPlusPreloadStyles,
    ],
  }
}
