/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeMonacoEditor: typeof import('./../components/code-monaco-editor/index.vue')['default']
    ContextMenu: typeof import('./../components/context-menu/index.vue')['default']
    DatasourceSelect: typeof import('./../components/generate/datasource-select/index.vue')['default']
    DeptPostSelect: typeof import('./../components/system/dept-post-select/index.vue')['default']
    DeptTree: typeof import('./../components/system/dept-tree/index.vue')['default']
    DeptTreeSelect: typeof import('./../components/system/dept-tree-select/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    IconSelect: typeof import('./../components/icon-select/index.vue')['default']
    MenuTreeCheck: typeof import('./../components/system/menu-tree-check/index.vue')['default']
    MenuTreeSelect: typeof import('./../components/system/menu-tree-select/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableToolBar: typeof import('./../components/table-tool-bar/index.vue')['default']
    TemplateGroupSelect: typeof import('./../components/generate/template-group-select/index.vue')['default']
    TypeMappingSelect: typeof import('./../components/generate/type-mapping-select/index.vue')['default']
    UserStatusTag: typeof import('./../components/system/user-status-tag/index.vue')['default']
    XhtCard: typeof import('./../components/xht-card/index.vue')['default']
    XhtPagination: typeof import('./../components/element-plus/xht-pagination/index.vue')['default']
  }
}
